development:
  :address: smtp.gmail.com
  :port: 587
  :authentication: plain
  :user_name: jmorazano
  :password: Raimundos2909
  :enable_starttls_auto: true
production:
  :address: smtp.gmail.com
  :port: 587
  :authentication: plain
  :user_name: jmorazano
  :password: Raimundos2909
  :enable_starttls_auto: true